
name: publish vscode

on:
  push:
    tags: 
      - 'v*'

jobs:
  publish-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i pnpm -g
      - run: pnpm add vsce -D
      - run: vsce package
      - run: vsce publish 
        env:
          VSCE_PAT: ${{secrets.ANT_SINPPENTS_TOKEN}}
